/* PROB 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

        1 million= 1,000,000
 */

import java.util.*;
class Prob2
{
    public static void main(String args[])
    {
        int first= 1, second= 2;
        int sum=2;
        while(second<4000000)
        {
            System.out.print(second+" ");
            int temp = second;
            second =first+ second;
            first= temp;
            if((second&1)==0)
                sum+=second;
        }
        System.out.println("\n"+sum);
    }
}

// + we can use bit manipulation to check for even or odd
