/**
 * QUESTION 12:
 *The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
 * The first ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred divisors?
 */

import java.util.*;
class Prob12
{
    static int factors(int n)
    {
        boolean[] composite=new boolean[n+1];
        int ret=1;

        for(int i=2;i<=n;i++)
        {
            int count=0;
            if(composite[i]) continue;

            while(n!=1 && n%i==0)
            {
                count++;
                n/=i;
            }

            for(int j=i*i;j<=n;j+=i)
                composite[j]= true;

            //System.out.println("for prime "+i+" count="+count);
            ret*= (count+1);
        }
        return ret;
    }

    public static void main(String[] args)
    {
        int i=1;

        while(true) {
            int prev_fact = factors(i % 2 != 0 ? i : i / 2);
            int curr_fact = factors((i + 1) % 2 != 0 ? (i + 1) : (i + 1) / 2);
            if (curr_fact * prev_fact >= 500) {
                System.out.println((i * (i + 1))/2);
                break;
            }

            i++;
        }
    }
}


/**
 * OBSERVATIONS: (i). nth triangular number can be find using the formula n*(n+1)/2
 *               (ii). n and n+1 are consecutive numbers so they will be co prime.
 *               (iii). so the total factors of nth triangular number is
 *                          = factors(n) * factors(n+1).
 */

/**
 * ALGORITHM: (i). Create a function that takes a number and gives it no of factors.
 *            (ii). traverse from 1 till we get our answer.
 *            (iii). check if factor(i) * factor(i+1)>= 500
 *
 *            (iv). ABOUT THE FUNCTION FACTOR(int n)
 *            (v). Using sieve to find the no of factors.
 */